# Generated by Django 5.2.7 on 2026-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
