# Generated by Django 5.2.7 on 2026-01-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_cv_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
