# Generated by Django 5.2.7 on 2026-01-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_old_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='raw_cv_data',
        ),
    ]
