# Generated by Django 5.2.7 on 2026-03-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_interviewsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewSession',
        ),
    ]
