# Generated by Django 5.2.7 on 2026-03-30 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_application_status_recommendedjob'),
        ('profiles', '0010_delete_interviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_content', models.JSONField(default=dict)),
                ('pre_chatbot_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshot', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_snapshots', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'job_profile_snapshots',
            },
        ),
    ]
