# Generated by Django 5.2.7 on 2026-04-05 14:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_userprofile_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embedding_education',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='embedding_experience',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='embedding_skills',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
