# Generated by Django 5.1.15 on 2026-04-21 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_embedding'),
        ('profiles', '0013_add_multi_vector_embeddings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('daily_invite_cap', models.PositiveSmallIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_campaigns', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outreach_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_handle', models.CharField(max_length=128)),
                ('target_name', models.CharField(blank=True, max_length=128)),
                ('target_role', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(choices=[('connect', 'Connect with note'), ('message', 'Direct message')], max_length=16)),
                ('payload', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_flight', 'In flight'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='profiles.outreachcampaign')),
            ],
            options={
                'db_table': 'outreach_actions',
                'ordering': ['queued_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='outreach_ac_campaig_caf5c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'target_handle', 'kind'), name='unique_action_per_target_per_campaign')],
            },
        ),
    ]
