# Generated by Django 5.1.15 on 2026-04-21 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_url_alter_recommendedjob_url'),
        ('profiles', '0014_outreachcampaign_outreachaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(choices=[('hiring_team', 'Meet the hiring team'), ('people_you_know', 'People you can reach out to'), ('company_people', 'Company employees')], max_length=32)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_targets', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discovered_targets',
                'ordering': ['-discovered_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'job', 'handle'), name='unique_discovered_target_per_user_job')],
            },
        ),
    ]
