# Generated by Django 5.1.15 on 2026-04-27 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_discoveredtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachActionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('actor', models.CharField(choices=[('extension', 'Extension'), ('user', 'User'), ('server_dispatch', 'Dispatcher'), ('server_recovery', 'Stale-recovery sweep'), ('server_finish', 'Campaign finish')], default='server_dispatch', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('attempts_after', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='profiles.outreachaction')),
            ],
            options={
                'db_table': 'outreach_action_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='outreach_ac_action__4e0f76_idx')],
            },
        ),
    ]
