# Generated by Django 5.1.15 on 2026-04-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_outreachactionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='summary_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
