# Generated by Django 5.1.15 on 2026-05-05 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_outreachcampaign_last_activity_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, default='', max_length=200)),
                ('locations', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('date_posted', models.CharField(choices=[('any', 'Any time'), ('24h', 'Past 24 hours'), ('week', 'Past week'), ('month', 'Past month')], default='week', max_length=16)),
                ('experience_levels', models.JSONField(default=list)),
                ('workplace_types', models.JSONField(default=list)),
                ('max_jobs', models.PositiveIntegerField(default=30)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_failed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_preferences',
            },
        ),
    ]
