# Generated by Django 5.1.15 on 2026-05-13 21:02

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_jobpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('concrete_rule', models.TextField(blank=True, default='')),
                ('sources', models.JSONField(default=list)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('roles', models.JSONField(default=list)),
                ('seniority', models.JSONField(default=list)),
                ('industries', models.JSONField(default=list)),
                ('region', models.CharField(db_index=True, default='global', max_length=16)),
                ('weight', models.CharField(default='medium', max_length=8)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('source_path', models.CharField(max_length=512)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'kb_id'],
            },
        ),
    ]
