# Generated by Django 5.1.15 on 2026-05-14 23:55

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_add_knowledge_chunks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_id', models.CharField(db_index=True, max_length=200)),
                ('source_type', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
                ('skill_tags', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'chunk_id'],
                'indexes': [models.Index(fields=['user', 'content_hash'], name='profiles_ca_user_id_4619d7_idx'), models.Index(fields=['user', 'source_type'], name='profiles_ca_user_id_5086a7_idx')],
                'unique_together': {('user', 'chunk_id')},
            },
        ),
    ]
