# Generated by Django 5.2.7 on 2026-01-07 19:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_setup_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
