# Generated by Django 5.2.7 on 2026-04-03 15:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_application_status_recommendedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
