# Generated by Django 5.1.15 on 2026-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedjob',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
