# Generated by Django 5.1.15 on 2026-05-05 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_url_alter_recommendedjob_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('params_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scrape_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('company', models.CharField(blank=True, default='', max_length=512)),
                ('company_url', models.URLField(blank=True, default='', max_length=2000)),
                ('location', models.CharField(blank=True, default='', max_length=512)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('posted', models.CharField(blank=True, default='', max_length=128)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=2000)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('unique_hash', models.CharField(max_length=64)),
                ('scrape_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='jobs.scrapejob')),
            ],
            options={
                'db_table': 'job_listings',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['scrape_job', 'source'], name='job_listing_scrape__a414f9_idx')],
                'unique_together': {('scrape_job', 'unique_hash')},
            },
        ),
    ]
