# Generated by Django 5.1.15 on 2026-05-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_scrapejob_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='extracted_skills_tiers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
