# Generated by Django 5.2.7 on 2026-01-01 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('html_content', models.TextField(blank=True)),
                ('ats_score', models.FloatField(default=0.0)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gap_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='analysis.gapanalysis')),
            ],
            options={
                'db_table': 'generated_resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
