# Generated by Django 5.2.7 on 2026-03-09 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_application_status_recommendedjob'),
        ('profiles', '0010_delete_interviewsession'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='name',
            field=models.CharField(default='Tailored Resume', max_length=200),
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'cover_letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
