# Generated by Django 5.1.15 on 2026-05-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_generatedresume_name_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
