# Generated by Django 5.1.15 on 2026-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outreach_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
