# Generated by Django 5.1.15 on 2026-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_outreach_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outreach_token_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
