from pydantic import BaseModel, Field, EmailStr, field_validator, model_validator
from typing import List, Optional, Any, Dict, Union
from pydantic import ConfigDict


# ============================================================
# CV / Profile Schemas
# ============================================================

class Skill(BaseModel):
    name: str
    proficiency: Optional[str] = Field(None, description="Beginner, Intermediate, Advanced, Expert")
    years: Optional[float] = None

class Experience(BaseModel):
    title: str
    company: str
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    description: Optional[Union[str, List[str]]] = Field(None, description="Role description. Can be a string or list of strings.")
    highlights: Optional[List[str]] = Field(default_factory=list, description="Bullet points of responsibilities or achievements")
    industry: Optional[str] = None
    location: Optional[str] = None
    achievements: Optional[List[str]] = Field(default_factory=list, description="Specific quantifiable achievements")
    model_config = ConfigDict(extra='allow')

class Education(BaseModel):
    degree: str
    institution: str
    graduation_year: Optional[str] = None
    field: Optional[str] = None
    gpa: Optional[str] = None
    honors: Optional[List[str]] = Field(default_factory=list)
    location: Optional[str] = None
    model_config = ConfigDict(extra='allow')

class Project(BaseModel):
    name: str
    description: Optional[Union[str, List[str]]] = None
    role: Optional[str] = None
    highlights: Optional[List[str]] = Field(default_factory=list, description="Bullet points detailing contributions")
    technologies: Optional[List[str]] = Field(default_factory=list)
    url: Optional[str] = None
    model_config = ConfigDict(extra='allow')

class Certification(BaseModel):
    name: str
    issuer: Optional[str] = None
    date: Optional[str] = None
    duration: Optional[str] = None
    url: Optional[str] = None

class ItemDetailed(BaseModel):
    title: str = ""
    organization: Optional[str] = None
    date: Optional[str] = None
    description: Optional[str] = None
    url: Optional[str] = None

class ResumeSchema(BaseModel):
    # Core identifying info
    full_name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    location: Optional[str] = None
    linkedin_url: Optional[str] = None
    github_url: Optional[str] = None
    portfolio_url: Optional[str] = None
    other_urls: Optional[List[str]] = Field(default_factory=list)
    
    # Generated content
    normalized_summary: Optional[str] = None
    objective: Optional[str] = None

    # Required structured lists
    skills: Optional[List[Skill]] = Field(default_factory=list)
    experiences: Optional[List[Experience]] = Field(default_factory=list)
    education: Optional[List[Education]] = Field(default_factory=list)
    
    # Optional structured lists
    projects: Optional[List[Project]] = Field(default_factory=list)
    certifications: Optional[List[Certification]] = Field(default_factory=list)
    
    # New Extended Fields for detailed extractions
    languages: Optional[List[str]] = Field(default_factory=list)
    volunteer_experience: Optional[List[ItemDetailed]] = Field(default_factory=list)
    awards: Optional[List[ItemDetailed]] = Field(default_factory=list)
    publications: Optional[List[ItemDetailed]] = Field(default_factory=list)
    speaking_engagements: Optional[List[ItemDetailed]] = Field(default_factory=list)
    patents: Optional[List[ItemDetailed]] = Field(default_factory=list)
    military_experience: Optional[List[ItemDetailed]] = Field(default_factory=list)
    hobbies: Optional[List[str]] = Field(default_factory=list)
    references: Optional[List[ItemDetailed]] = Field(default_factory=list)
    courses: Optional[List[ItemDetailed]] = Field(default_factory=list)
    
    # Allow extra fields generated by LLM dynamically
    model_config = {
        "extra": "allow"
    }


# ============================================================
# LLM Output Schemas (used by get_structured_llm)
# ============================================================

class GapAnalysisResult(BaseModel):
    """Legacy flat-list gap analysis output (kept for backward compat with
    benchmarks + any caller that still wants the simple shape). New code
    should use TieredGapAnalysisResult below."""
    critical_missing_skills: List[str] = Field(default_factory=list, description="Hard technical skills the user clearly lacks")
    soft_skill_gaps: List[str] = Field(default_factory=list, description="Soft skills gaps if required and missing")
    matched_skills: List[str] = Field(default_factory=list, description="Skills the user has that match requirements")
    similarity_score: float = Field(default=0.5, description="Overall match score from 0.0 to 1.0 based on skills, experience relevance, and seniority fit")


# --------------------------------------------------------------------------
# Tier-aware gap analysis (v2, 2026-05-14)
# --------------------------------------------------------------------------

class MatchedSkill(BaseModel):
    """A JD-required skill the candidate clearly has.

    The evidence_quote is the verbatim phrase from the profile that proves
    it — surfaced in the chip's hover tooltip on the gap page. String
    fields use Optional + field_validator coercion (rather than max_length=N
    on Field) because Groq's tool-call API enforces max_length BEFORE
    Pydantic gets the response — a 153-char quote there breaks the whole
    structured call. We accept whatever the LLM emits, coerce null → "",
    and truncate in Python.
    """
    name: str = Field(description="Skill name, copied verbatim from the JD's tier list.")
    evidence_source: Optional[str] = Field(
        default="",
        description=(
            "Where the proof was found. One of: 'skills', 'experience', "
            "'projects', 'certifications', 'github', 'scholar', 'kaggle', "
            "'education', 'multiple'. Empty string when no single source "
            "stands out. Pick the strongest single source when possible."
        ),
    )
    evidence_quote: Optional[str] = Field(
        default="",
        description=(
            "Short verbatim quote from the profile proving the match. Target "
            "≤140 chars; longer responses get truncated client-side. Empty "
            "string when no specific quote applies."
        ),
    )

    @field_validator("evidence_source", "evidence_quote", mode="before")
    @classmethod
    def _coerce_str(cls, v):
        if v is None:
            return ""
        s = str(v).strip()
        return s[:140]


class MissingSkill(BaseModel):
    """A JD-required skill the candidate does NOT have, with a proximity score
    indicating how close they are based on adjacent evidence.

    proximity is strictly less than 1.0 — a skill at 1.0 belongs in
    matched_*, not missing_*. The Pydantic validator below enforces this; the
    prompt also tells the LLM to obey it, and gap_analyzer retries once when
    a 1.0 leaks through.

    String fields are Optional with `_coerce_str` rather than `max_length`
    constraints because Groq's tool-call API rejects over-long strings BEFORE
    Pydantic sees them. Truncation happens in the validator.
    """
    name: str = Field(description="Skill name, copied verbatim from the JD's tier list.")
    source_quote: Optional[str] = Field(
        default="",
        description=(
            "Short JD sentence that asked for this skill. Target ≤140 chars; "
            "truncated client-side if longer. Empty string acceptable."
        ),
    )
    proximity: float = Field(
        default=0.0,
        ge=0.0,
        lt=1.0,
        description=(
            "How close the candidate is to having this skill on [0.0, 1.0). "
            "Anchor scale: 0.0 no related evidence; 0.2 vaguely adjacent "
            "domain; 0.4 one adjacent skill present; 0.6 multiple adjacent "
            "OR coursework-level; 0.8 exact skill mentioned but thin evidence "
            "OR lower seniority than asked. 1.0 is FORBIDDEN — those belong "
            "in matched_*."
        ),
    )
    proximity_reason: Optional[str] = Field(
        default="",
        description=(
            "Human reason for the proximity score. Target ≤120 chars; "
            "truncated client-side if longer."
        ),
    )
    bridge_hint: Optional[str] = Field(
        default=None,
        description=(
            "Optional concrete next step the candidate could take to close "
            "this gap. Target ≤140 chars. Omit (use null) when you have "
            "nothing concrete — do not invent generic advice."
        ),
    )

    @field_validator("source_quote", "proximity_reason", mode="before")
    @classmethod
    def _coerce_str_140(cls, v):
        if v is None:
            return ""
        s = str(v).strip()
        return s[:140]

    @field_validator("bridge_hint", mode="before")
    @classmethod
    def _coerce_optional_140(cls, v):
        if v is None:
            return None
        s = str(v).strip()
        if not s:
            return None
        return s[:140]

    @field_validator("proximity")
    @classmethod
    def reject_one(cls, v: float) -> float:
        # The Field(lt=1.0) constraint already enforces this; we add an
        # explicit message so the retry loop in gap_analyzer can show the
        # LLM exactly why we rejected the value.
        if v >= 1.0:
            raise ValueError(
                "Skills with proximity 1.0 must be in matched_must_have or "
                "matched_nice_to_have, not missing_*. Re-route the skill or "
                "lower the proximity (0.8 = exact skill present but thin "
                "evidence)."
            )
        return v


class TieredGapAnalysisResult(BaseModel):
    """Output schema for gap_analyzer.compute_gap_analysis v2.

    Four tier-split lists drive the three on-screen columns:
        UI MATCHED column      = matched_must_have + matched_nice_to_have
                                  (must-haves rendered with a ★)
        UI CRITICAL MISSING    = missing_must_have
        UI SOFT GAPS           = missing_nice_to_have

    soft_skill_gaps captures non-skill observations (seniority gap, career
    transition risk) that aren't a single skill — surfaced as a banner /
    side-note, not a draggable chip.
    """
    matched_must_have: List[MatchedSkill] = Field(default_factory=list)
    matched_nice_to_have: List[MatchedSkill] = Field(default_factory=list)
    missing_must_have: List[MissingSkill] = Field(default_factory=list)
    missing_nice_to_have: List[MissingSkill] = Field(default_factory=list)
    soft_skill_gaps: List[str] = Field(
        default_factory=list,
        description=(
            "Free-text observations about seniority / career transition / "
            "non-skill fit signals. NOT skill names. ≤20 words each."
        ),
    )

class SkillListResult(BaseModel):
    """Output schema for skill_extractor.py — flat list (kept for backward compat)."""
    skills: List[str] = Field(default_factory=list, description="List of extracted skill names")


class JobExtractionResult(BaseModel):
    """Unified output of jobs.services.skill_extractor.extract_job_info.

    The LLM splits skills into Must-Have vs Nice-to-Have using the JD's section
    cues ("Required" / "Must-have" / "Responsibilities" → must_have;
    "Nice to have" / "Desirable" / "Bonus" / "Plus" → nice_to_have). The flat
    `Job.extracted_skills` field downstream is the deduped union of both.
    `domain` is a short noun phrase (canonicalized post-hoc against an alias
    map) capturing the industry the role serves.
    """
    must_have_skills: List[str] = Field(
        default_factory=list,
        description="Skills the JD lists as required / must-have / core responsibilities.",
    )
    nice_to_have_skills: List[str] = Field(
        default_factory=list,
        description="Skills the JD lists as nice-to-have / desirable / bonus / plus.",
    )
    domain: str = Field(
        default="",
        description=(
            "Industry domain inferred from the JD (free text, canonicalized "
            "post-hoc). Examples: 'Financial Services', 'Healthcare', "
            "'E-commerce', 'Gaming'. Empty when no clear signal."
        ),
    )


class ExtractedExperienceBullet(BaseModel):
    """A generated resume bullet based on the user's conversational reply."""
    company_or_project_name: str = Field(description="The name of the company or project this bullet applies to (must match an existing one if possible, or 'General')")
    bullet_point: str = Field(description="A concise, STAR-format bullet point (max 120 chars) summarizing the achievement or skill application.")

class ChatReplyAnalysis(BaseModel):
    """Sub-schema for interviewer.py — analysis of user's reply"""
    is_valid: bool = True
    quality_score: int = Field(default=5, description="0-10 quality score")
    clarification_prompt: str = Field(default="", description="Ask for more details if is_valid is false")
    skills_to_add: List[Skill] = Field(default_factory=list)
    all_technologies_mentioned: List[str] = Field(default_factory=list)
    new_experience_bullets: List[ExtractedExperienceBullet] = Field(default_factory=list, description="Extract a formal resume bullet ONLY if the user described an actionable achievement. Max 1 item.")

class ChatNextQuestion(BaseModel):
    """Sub-schema for interviewer.py — next question generation"""
    question: str = Field(default="Tell me about your background.", description="Next conversational message. Include a brief acknowledgment of the user's answer, then naturally ask about the next skill. 2-4 sentences, max 60 words. Use **bold** for skill names.")
    topic_skill: str = Field(default="general", description="The skill being asked about")

class ChatTurnResult(BaseModel):
    """Output schema for interviewer.py"""
    reply_analysis: ChatReplyAnalysis = Field(default_factory=ChatReplyAnalysis)
    next_question_generation: ChatNextQuestion = Field(default_factory=ChatNextQuestion)

class SemanticValidationResult(BaseModel):
    """Output schema for semantic_validator.py"""
    makes_sense: bool = True
    clarification_question: str = ""

class GuardrailResult(BaseModel):
    """Output schema for interviewer.py guardrail check"""
    valid: bool = True
    reason: str = ""

class OutreachCampaignResult(BaseModel):
    """Output schema for outreach_generator.py"""
    linkedin_message: str = ""
    cold_email_subject: str = ""
    cold_email_body: str = ""

def _coerce_null_strings(values: dict, fields: tuple) -> dict:
    """Replace None with "" on string-typed fields the LLM may emit as null.

    Groq's tool-call validator strict-checks declared `string` fields against
    JSON null and rejects the call. The model legitimately emits null for
    blank values, so we coerce them in a `before` validator instead of
    making every field Optional[str] (which would loosen the contract for
    every other consumer).
    """
    if not isinstance(values, dict):
        return values
    for f in fields:
        if values.get(f) is None:
            values[f] = ""
    return values


def _flatten_string_list(items, *, prefer_keys: tuple = ('description', 'text', 'name', 'value')) -> list:
    """Coerce a list-of-objects shape into a list-of-strings.

    The Groq model sometimes wraps each list item as a single-key object
    (e.g. `[{"description": "..."}, ...]` instead of `["...", ...]`). The
    schema declares plain strings, so without this coercion the call fails
    with `expected string, but got object`. Tries the standard wrapper
    keys in order; falls back to the first string value or the str() of
    the entire item.
    """
    if items is None:
        return []
    if isinstance(items, str):
        return [line.strip() for line in items.split('\n') if line.strip()]
    out = []
    for item in items:
        if isinstance(item, str):
            s = item.strip()
            if s:
                out.append(s)
            continue
        if isinstance(item, dict):
            for k in prefer_keys:
                v = item.get(k)
                if isinstance(v, str) and v.strip():
                    out.append(v.strip())
                    break
            else:
                # No preferred key matched; pull the first string value.
                for v in item.values():
                    if isinstance(v, str) and v.strip():
                        out.append(v.strip())
                        break
        else:
            s = str(item).strip()
            if s:
                out.append(s)
    return out


class ResumeExperience(BaseModel):
    title: str = ""
    company: str = ""
    duration: str = ""
    location: str = ""
    industry: str = ""
    start_date: str = ""
    end_date: str = ""
    description: Union[str, List[str]] = Field(default_factory=list)

    @model_validator(mode='before')
    @classmethod
    def normalize(cls, values):
        if not isinstance(values, dict):
            return values
        # Coerce null → "" for string fields the LLM may emit as null.
        values = _coerce_null_strings(values, (
            'title', 'company', 'duration', 'location', 'industry',
            'start_date', 'end_date',
        ))
        desc = values.get('description', [])
        hl = values.get('highlights')
        hl_list = _flatten_string_list(hl) if isinstance(hl, list) else []
        # Groq's tool-call validator strict-rejects `null` on Union types,
        # and the recovery path that re-parses failed_generation hits the
        # same null. Treat null as "no description".
        if desc is None:
            desc_list = []
        elif isinstance(desc, str):
            desc_list = [d.strip() for d in desc.split('\n') if d.strip()]
        elif isinstance(desc, list):
            desc_list = _flatten_string_list(desc)
        else:
            desc_list = []
        # The LLM sometimes splits content: description holds a summary
        # sentence and highlights holds the actual bullets. Or it ignores
        # the field-mapping rule entirely and puts ALL bullets in
        # highlights with description=null. The docx exporter only reads
        # `description`, so merge highlights in:
        #   - description empty + highlights present  →  use highlights
        #   - description has a single string         →  prepend it, then
        #                                                append highlights
        #     (treats description as prelude / summary line)
        #   - description already has multiple list   →  trust the LLM,
        #     entries                                    drop highlights
        #                                                (it's likely dup
        #                                                content)
        if not desc_list and hl_list:
            desc_list = hl_list
        elif len(desc_list) == 1 and hl_list:
            desc_list = desc_list + hl_list
        values['description'] = desc_list
        return values

class ResumeProject(BaseModel):
    name: str = ""
    description: Union[str, List[str]] = Field(default_factory=list)
    url: str = ""
    technologies: List[str] = Field(default_factory=list)
    highlights: List[str] = Field(default_factory=list)

    @model_validator(mode='before')
    @classmethod
    def normalize(cls, values):
        if not isinstance(values, dict):
            return values
        values = _coerce_null_strings(values, ('name', 'url'))
        desc = values.get('description', [])
        hl = values.get('highlights')
        hl_list = _flatten_string_list(hl) if isinstance(hl, list) else []
        # null → [] + same merge rules as ResumeExperience above.
        if desc is None:
            desc_list = []
        elif isinstance(desc, str):
            desc_list = [d.strip() for d in desc.split('\n') if d.strip()]
        elif isinstance(desc, list):
            desc_list = _flatten_string_list(desc)
        else:
            desc_list = []
        if not desc_list and hl_list:
            desc_list = hl_list
        elif len(desc_list) == 1 and hl_list:
            desc_list = desc_list + hl_list
        values['description'] = desc_list
        # Accept comma-separated technologies string from the editor form,
        # AND list-of-objects from a tool-call mode the LLM sometimes uses.
        tech = values.get('technologies', [])
        if isinstance(tech, str):
            values['technologies'] = [t.strip() for t in tech.split(',') if t.strip()]
        elif isinstance(tech, list):
            values['technologies'] = _flatten_string_list(tech)
        # highlights is List[str]; the model sometimes wraps as
        # [{description: "..."}]. Flatten so the field validates.
        h = values.get('highlights', [])
        if isinstance(h, list):
            values['highlights'] = _flatten_string_list(h)
        return values

class ResumeCertification(BaseModel):
    name: str = ""
    issuer: str = ""
    date: str = ""
    duration: str = ""
    url: str = ""

    @model_validator(mode='before')
    @classmethod
    def normalize(cls, values):
        if not isinstance(values, dict):
            return values
        return _coerce_null_strings(values, ('name', 'issuer', 'date', 'duration', 'url'))

class ResumeEducation(BaseModel):
    degree: str = ""
    institution: str = ""
    year: str = ""
    field: str = ""
    gpa: str = ""
    location: str = ""
    honors: List[str] = Field(default_factory=list)

    @model_validator(mode='before')
    @classmethod
    def normalize(cls, values):
        if not isinstance(values, dict):
            return values
        values = _coerce_null_strings(values, (
            'degree', 'institution', 'year', 'field', 'gpa', 'location',
        ))
        h = values.get('honors', [])
        if isinstance(h, str):
            values['honors'] = [line.strip() for line in h.split('\n') if line.strip()]
        elif isinstance(h, list):
            values['honors'] = _flatten_string_list(h)
        return values

class ResumeContentResult(BaseModel):
    """Output schema for resume_generator.py — superset of master profile fields.

    The editor at /resumes/edit/ surfaces every field defined here. Master-profile
    fields (UserProfile.data_content) get pulled into the matching field on
    generation or via sync_from_master. The LLM may still drop ATS-discouraged
    fields (objective, GPA) for its own resume drafts; users can re-add them
    via the editor.
    """
    professional_title: str = ""
    professional_summary: str = ""
    objective: str = ""
    skills: List[str] = Field(default_factory=list)
    experience: List[ResumeExperience] = Field(default_factory=list)
    education: List[ResumeEducation] = Field(default_factory=list)
    projects: List[ResumeProject] = Field(default_factory=list)
    certifications: List[ResumeCertification] = Field(default_factory=list)
    languages: List[str] = Field(default_factory=list)
    model_config = {"extra": "allow"}

    @model_validator(mode='before')
    @classmethod
    def normalize(cls, values):
        if not isinstance(values, dict):
            return values
        # Top-level string fields may come back as null.
        values = _coerce_null_strings(values, (
            'professional_title', 'professional_summary', 'objective',
        ))
        # `skills` is List[str] but the LLM sometimes wraps each entry as
        # {name: "...", proficiency: null, years: null}. Flatten.
        s = values.get('skills', [])
        if isinstance(s, list):
            values['skills'] = _flatten_string_list(s)
        # `languages` same shape risk.
        lg = values.get('languages', [])
        if isinstance(lg, list):
            values['languages'] = _flatten_string_list(lg)
        return values

class SectionFilterResult(BaseModel):
    """Output schema for resume_generator.py section filtering"""
    include_sections: List[str] = Field(default_factory=list)
    exclude_sections: List[str] = Field(default_factory=list)
    reasoning: str = ""

class LearningPathItem(BaseModel):
    """Single item in a learning path.

    `resources` is a list of dicts with the keys `name` / `url` / `provider`
    (typed loosely as Dict[str, str] for LLM-friendly output). The template
    renders each resource as a clickable link when `url` is non-empty.
    """
    skill: str = ""
    importance: str = ""
    resources: List[Dict[str, str]] = Field(default_factory=list)
    project_idea: str = ""
    time_estimate: str = ""

class LearningPathResult(BaseModel):
    """Output schema for learning_path_generator.py"""
    items: List[LearningPathItem] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Project enrichment + dedupe (Phase 1 of the GitHub/Scholar/Kaggle → resume
# pipeline). The aggregators pull raw signal data; project_enricher.py turns
# each repo / paper / competition into a project-shaped artifact with
# resume bullets; project_dedupe.py decides per pair whether the enriched
# project is the same as something the user already has typed in.
# ---------------------------------------------------------------------------

class EnrichedProject(BaseModel):
    """One source-derived project with resume-ready content.

    `source` is one of {"github", "scholar", "kaggle"}; `source_id` is the
    aggregator's stable identifier for the item (repo full_name, paper
    citation_id, competition slug). `source_url` is the canonical web URL.
    """
    name: str = ""
    summary: str = ""
    tech_stack: List[str] = Field(default_factory=list)
    bullets: List[str] = Field(default_factory=list)
    source: str = ""
    source_id: str = ""
    source_url: str = ""

    @model_validator(mode='before')
    @classmethod
    def normalize(cls, values):
        # Allow LLM to return tech_stack as a comma-separated string
        ts = values.get('tech_stack', [])
        if isinstance(ts, str):
            values['tech_stack'] = [t.strip() for t in ts.split(',') if t.strip()]
        # Allow bullets as newline-separated string too
        b = values.get('bullets', [])
        if isinstance(b, str):
            values['bullets'] = [line.strip() for line in b.split('\n') if line.strip()]
        return values


class EnrichedProjectBatch(BaseModel):
    """LLM output schema for batch enrichment of multiple repos at once."""
    projects: List[EnrichedProject] = Field(default_factory=list)


class DedupeDecision(BaseModel):
    """One per-pair dedupe verdict from the LLM.

    `enriched_index` is the index into the enriched-projects list; `typed_index`
    is the index into the user's typed projects (matched_skills if action is
    not "add_new"). When `action == "add_new"`, typed_index is -1.

    `action`:
      - "merge": the two represent the same project; keep both signals
        (we'll union tech stacks + concatenate bullets, prefer typed name).
      - "keep_existing": same project; keep the typed version, drop enriched.
      - "keep_new": same project; replace typed with enriched.
      - "add_new": enriched has no typed counterpart; add it as a new project.

    `confidence` is the LLM's stated confidence in the verdict (0–1).
    """
    enriched_index: int = -1
    typed_index: int = -1
    action: str = "add_new"
    confidence: float = 0.0
    reason: str = ""


class DedupeBatch(BaseModel):
    """LLM output schema for batched dedupe across all (typed, enriched) pairs."""
    decisions: List[DedupeDecision] = Field(default_factory=list)


class KeywordCandidate(BaseModel):
    """One suggested keyword with a brief plain-language reason."""
    keyword: str = Field(default="", description="Job-board search keyword. 1-3 words, no parens, no seniority words.")
    why: str = Field(default="", description="One short phrase (under 12 words) explaining why this fits.")


class SuggestedJobPreferences(BaseModel):
    """LLM output for the 'auto-fill preferences from my profile' button.

    Restricted to fields the LLM can genuinely reason about from a CV +
    signals — sources/date_posted/max_jobs are user policy, not profile-derived,
    so they're left to the form's defaults.
    """
    keyword: str = Field(default="", description="The single TOP keyword (also the first item in keyword_candidates).")
    keyword_candidates: List[KeywordCandidate] = Field(
        default_factory=list,
        description="3-5 distinct candidate roles ranked by fit — different angles on the user's profile, not synonyms. Each anchored on a skill cluster the user actually demonstrates.",
    )
    locations: List[str] = Field(default_factory=list, description="2-3 locations the user could realistically target, ordered by likely fit. Include 'Remote' if appropriate.")
    experience_levels: List[str] = Field(default_factory=list, description="One or more of: internship, entry, associate, mid_senior, director, executive. Pick the user's current band plus the next one up.")
    workplace_types: List[str] = Field(default_factory=list, description="Subset of: onsite, remote, hybrid. Reflect what's plausible given location + recent roles.")
    rationale: str = Field(default="", description="One short sentence explaining the choices, surfaced to the user.")
