from pydantic import BaseModel, Field, EmailStr, model_validator
from typing import List, Optional, Any, Dict, Union
from pydantic import ConfigDict


# ============================================================
# CV / Profile Schemas
# ============================================================

class Skill(BaseModel):
    name: str
    proficiency: Optional[str] = Field(None, description="Beginner, Intermediate, Advanced, Expert")
    years: Optional[float] = None

class Experience(BaseModel):
    title: str
    company: str
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    description: Optional[Union[str, List[str]]] = Field(None, description="Role description. Can be a string or list of strings.")
    highlights: Optional[List[str]] = Field(default_factory=list, description="Bullet points of responsibilities or achievements")
    industry: Optional[str] = None
    location: Optional[str] = None
    achievements: Optional[List[str]] = Field(default_factory=list, description="Specific quantifiable achievements")
    model_config = ConfigDict(extra='allow')

class Education(BaseModel):
    degree: str
    institution: str
    graduation_year: Optional[str] = None
    field: Optional[str] = None
    gpa: Optional[str] = None
    honors: Optional[List[str]] = Field(default_factory=list)
    location: Optional[str] = None
    model_config = ConfigDict(extra='allow')

class Project(BaseModel):
    name: str
    description: Optional[Union[str, List[str]]] = None
    role: Optional[str] = None
    highlights: Optional[List[str]] = Field(default_factory=list, description="Bullet points detailing contributions")
    technologies: Optional[List[str]] = Field(default_factory=list)
    url: Optional[str] = None
    model_config = ConfigDict(extra='allow')

class Certification(BaseModel):
    name: str
    issuer: Optional[str] = None
    date: Optional[str] = None
    duration: Optional[str] = None
    url: Optional[str] = None

class ItemDetailed(BaseModel):
    title: str = ""
    organization: Optional[str] = None
    date: Optional[str] = None
    description: Optional[str] = None
    url: Optional[str] = None

class ResumeSchema(BaseModel):
    # Core identifying info
    full_name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    location: Optional[str] = None
    linkedin_url: Optional[str] = None
    github_url: Optional[str] = None
    portfolio_url: Optional[str] = None
    other_urls: Optional[List[str]] = Field(default_factory=list)
    
    # Generated content
    normalized_summary: Optional[str] = None
    objective: Optional[str] = None

    # Required structured lists
    skills: Optional[List[Skill]] = Field(default_factory=list)
    experiences: Optional[List[Experience]] = Field(default_factory=list)
    education: Optional[List[Education]] = Field(default_factory=list)
    
    # Optional structured lists
    projects: Optional[List[Project]] = Field(default_factory=list)
    certifications: Optional[List[Certification]] = Field(default_factory=list)
    
    # New Extended Fields for detailed extractions
    languages: Optional[List[str]] = Field(default_factory=list)
    volunteer_experience: Optional[List[ItemDetailed]] = Field(default_factory=list)
    awards: Optional[List[ItemDetailed]] = Field(default_factory=list)
    publications: Optional[List[ItemDetailed]] = Field(default_factory=list)
    speaking_engagements: Optional[List[ItemDetailed]] = Field(default_factory=list)
    patents: Optional[List[ItemDetailed]] = Field(default_factory=list)
    military_experience: Optional[List[ItemDetailed]] = Field(default_factory=list)
    hobbies: Optional[List[str]] = Field(default_factory=list)
    references: Optional[List[ItemDetailed]] = Field(default_factory=list)
    courses: Optional[List[ItemDetailed]] = Field(default_factory=list)
    
    # Allow extra fields generated by LLM dynamically
    model_config = {
        "extra": "allow"
    }


# ============================================================
# LLM Output Schemas (used by get_structured_llm)
# ============================================================

class GapAnalysisResult(BaseModel):
    """Output schema for gap_analyzer.py"""
    critical_missing_skills: List[str] = Field(default_factory=list, description="Hard technical skills the user clearly lacks")
    soft_skill_gaps: List[str] = Field(default_factory=list, description="Soft skills gaps if required and missing")
    matched_skills: List[str] = Field(default_factory=list, description="Skills the user has that match requirements")
    similarity_score: float = Field(default=0.5, description="Overall match score from 0.0 to 1.0 based on skills, experience relevance, and seniority fit")

class SkillListResult(BaseModel):
    """Output schema for skill_extractor.py"""
    skills: List[str] = Field(default_factory=list, description="List of extracted skill names")

class ExtractedExperienceBullet(BaseModel):
    """A generated resume bullet based on the user's conversational reply."""
    company_or_project_name: str = Field(description="The name of the company or project this bullet applies to (must match an existing one if possible, or 'General')")
    bullet_point: str = Field(description="A concise, STAR-format bullet point (max 120 chars) summarizing the achievement or skill application.")

class ChatReplyAnalysis(BaseModel):
    """Sub-schema for interviewer.py — analysis of user's reply"""
    is_valid: bool = True
    quality_score: int = Field(default=5, description="0-10 quality score")
    clarification_prompt: str = Field(default="", description="Ask for more details if is_valid is false")
    skills_to_add: List[Skill] = Field(default_factory=list)
    all_technologies_mentioned: List[str] = Field(default_factory=list)
    new_experience_bullets: List[ExtractedExperienceBullet] = Field(default_factory=list, description="Extract a formal resume bullet ONLY if the user described an actionable achievement. Max 1 item.")

class ChatNextQuestion(BaseModel):
    """Sub-schema for interviewer.py — next question generation"""
    question: str = Field(default="Tell me about your background.", description="Next conversational message. Include a brief acknowledgment of the user's answer, then naturally ask about the next skill. 2-4 sentences, max 60 words. Use **bold** for skill names.")
    topic_skill: str = Field(default="general", description="The skill being asked about")

class ChatTurnResult(BaseModel):
    """Output schema for interviewer.py"""
    reply_analysis: ChatReplyAnalysis = Field(default_factory=ChatReplyAnalysis)
    next_question_generation: ChatNextQuestion = Field(default_factory=ChatNextQuestion)

class SemanticValidationResult(BaseModel):
    """Output schema for semantic_validator.py"""
    makes_sense: bool = True
    clarification_question: str = ""

class GuardrailResult(BaseModel):
    """Output schema for interviewer.py guardrail check"""
    valid: bool = True
    reason: str = ""

class OutreachCampaignResult(BaseModel):
    """Output schema for outreach_generator.py"""
    linkedin_message: str = ""
    cold_email_subject: str = ""
    cold_email_body: str = ""

class ResumeExperience(BaseModel):
    title: str = ""
    company: str = ""
    duration: str = ""
    description: str = ""

class ResumeProject(BaseModel):
    name: str = ""
    description: Union[str, List[str]] = ""
    url: str = ""

    @model_validator(mode='before')
    @classmethod
    def normalize_description(cls, values):
        desc = values.get('description', '')
        if isinstance(desc, list):
            values['description'] = '\n'.join(str(item) for item in desc)
        return values

class ResumeCertification(BaseModel):
    name: str = ""
    issuer: str = ""
    date: str = ""
    url: str = ""

class ResumeEducation(BaseModel):
    degree: str = ""
    institution: str = ""
    year: str = ""

class ResumeContentResult(BaseModel):
    """Output schema for resume_generator.py"""
    professional_title: str = ""
    professional_summary: str = ""
    skills: List[str] = Field(default_factory=list)
    experience: List[ResumeExperience] = Field(default_factory=list)
    education: List[ResumeEducation] = Field(default_factory=list)
    projects: List[ResumeProject] = Field(default_factory=list)
    certifications: List[ResumeCertification] = Field(default_factory=list)
    languages: List[str] = Field(default_factory=list)
    model_config = {"extra": "allow"}

class SectionFilterResult(BaseModel):
    """Output schema for resume_generator.py section filtering"""
    include_sections: List[str] = Field(default_factory=list)
    exclude_sections: List[str] = Field(default_factory=list)
    reasoning: str = ""

class LearningPathItem(BaseModel):
    """Single item in a learning path"""
    skill: str = ""
    importance: str = ""
    resources: List[Dict[str, str]] = Field(default_factory=list)
    project_idea: str = ""

class LearningPathResult(BaseModel):
    """Output schema for learning_path_generator.py"""
    items: List[LearningPathItem] = Field(default_factory=list)
