# Generated by Django 5.1.15 on 2026-05-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_gapanalysis_user_alter_gapanalysis_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysis',
            name='avg_proximity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='match_band',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='matched_must_have',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='matched_nice_to_have',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='missing_must_have',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='missing_nice_to_have',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
